/**
 * @file api-client.ts
 * @description Generic HTTP client for external provider APIs with retry logic and standard logging.
 */

import { logger } from '@/lib/logger';
import { ProviderError, ProviderErrorCode } from '@/providers/errors';

/** Options for secure fetch requests. */
export interface RequestOptions extends RequestInit {
  retryLimit?: number;
  timeout?: number;
  raw?: boolean;
}

/**
 * Robust fetcher with automatic retries for common server errors (503, 504, 429).
 * @template T - The expected response type (ignored if options.raw is true).
 * @param url - The full URL to fetch.
 * @param options - Fetch options including retry limits, timeouts, and raw response flag.
 * @param retryCount - Current retry attempt.
 * @returns The parsed JSON response OR the raw Response object if options.raw is true.
 */
export async function secureFetch<T = unknown>(
  url: string,
  options: RequestOptions = {},
  retryCount = 0,
): Promise<T | Response> {
  const { retryLimit = 2, raw = false, timeout, ...fetchOptions } = options;

  const finalOptions = { ...fetchOptions };

  // Inject timeout abort signal if requested
  if (timeout !== undefined && typeof AbortSignal !== 'undefined' && typeof AbortSignal.timeout === 'function') {
    finalOptions.signal = AbortSignal.timeout(timeout);
  }

  try {
    const response = await fetch(url, finalOptions);

    // Handle temporary server errors or rate limits
    if ([429, 503, 504].includes(response.status) && retryCount < retryLimit) {
      const delay = 1000 * (retryCount + 1);
      logger.warn(`API received ${response.status} for ${url}. Retrying in ${delay}ms...`);
      await new Promise((resolve) => setTimeout(resolve, delay));
      return secureFetch<T>(url, options, retryCount + 1);
    }

    if (!response.ok) {
      const text = await response.text();
      logger.error({ status: response.status, url, body: text }, 'External API Error');

      throw new ProviderError(
        resolveErrorCode(response.status),
        `API Error: ${response.status} ${response.statusText}`,
        { status: response.status, body: text }
      );
    }

    if (raw) {
      return response;
    }

    return response.json();
  } catch (error) {
    if (
      retryCount < retryLimit &&
      !(error instanceof ProviderError) &&
      !(error instanceof DOMException && error.name === 'TimeoutError')
    ) {
      logger.warn({ error, url }, 'Network Error, retrying...');
      return secureFetch<T>(url, options, retryCount + 1);
    }

    // Map native timeout errors natively generated by AbortSignal
    if (error instanceof DOMException && error.name === 'TimeoutError') {
      logger.error({ url, timeout }, 'API Request Timed Out');
      throw new ProviderError(ProviderErrorCode.TIMEOUT, `Request timed out after ${timeout}ms`, error);
    }

    throw error;
  }
}
function resolveErrorCode(status: number): ProviderErrorCode {
  if (status === 401 || status === 403) return ProviderErrorCode.AUTH_ERROR;
  if (status === 404) return ProviderErrorCode.NOT_FOUND;
  if (status === 429) return ProviderErrorCode.RATE_LIMIT;
  if (status >= 500) return ProviderErrorCode.SERVICE_UNAVAILABLE;
  return ProviderErrorCode.INTERNAL_ERROR;
}

